---
title: "mapped_reads_raref"
output: html_document
date: "2024-04-24"
---

-################################################################################

# Libraries
```{r}
library(rstatix)
library(tidyverse)
```

-################################################################################

# Import data
```{r}
reads.data <- read.delim("../data/nb_reads.txt", header = TRUE, sep = "\t", dec = ",", row.names = 1)
```

Metadata
```{r}
metadata <- read.delim("../data/samples_metadata.txt", header = TRUE, sep = "\t", dec = ".", row.names = 1)
metadata <- metadata %>% arrange(row.names(.))
metadata <- metadata %>% mutate(across(c(plant_clade,plant_order,plant_family,host_species,tree), as.factor))
reads.data$host_species <- metadata$host_species
metadata$host_species <- factor(x = metadata$host_species, levels = c("ABBA","THOC","ACSA","FAGR","COCO"))
reads.data$host_species <- factor(x = reads.data$host_species, levels = c("ABBA","THOC","ACSA","FAGR","COCO"))
```

-################################################################################

# Filtered paired-end reads ~ host species

Check if number of quality filtered reads differ by host species
```{r}
summary(lm(reads.data$filtered_pairs ~ reads.data$host_species))
plot(lm(reads.data$filtered_pairs ~ reads.data$host_species))
```

ggplot
```{r}
reads.data.ggplot <- reads.data
reads.data.ggplot$filtered_pairs <- reads.data.ggplot$filtered_pairs/1000000

ggplot(reads.data.ggplot, aes(x = host_species, y = filtered_pairs)) +
geom_boxplot(alpha = 1, aes(fill = host_species), show.legend = FALSE, outlier.shape = NA)+
geom_point(aes(color = host_species), 
           position = position_jitter(0.075), 
           shape = 16, 
           size = 3, show.legend = FALSE)+
scale_fill_manual(values=c("#63AFF9","#1EA670","#CA0E78","#F39635","#6104BB"))+
scale_color_manual(values=c("black","black","black","black","black"))+
labs(x = "Host Species", 
     y = "Filtered paired-end reads (M)")+
scale_x_discrete(labels = c("ABBA" = "A. balsamea", "THOC" = "T. occidentalis","ACSA" = "A. saccharum", "FAGR" = "F. grandifolia", "COCO" = "C. cornuta"))+
theme_bw()+
theme(text = element_text(family = "Arial"),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(color = "black", size = 11, angle = 0, hjust = 0.5, vjust = 0, face = "italic"),
      axis.text.y = element_text(color = "black", size = 11, angle = 0, hjust = 0, vjust = 0.5),  
      axis.title.x = element_text(color = "black", size = 13, angle = 0, hjust = 0.5, vjust = -1, face = "bold"),
      axis.title.y = element_text(color = "black", size = 13, angle = 90, hjust = 0.5, vjust = 2, face = "bold")
      )
ggsave("../figures/figure_S4_filtered_read_pairs_by_host.tiff", width = 6, height = 4)
```


-################################################################################

# % Mapped reads ~ host species

Check if % of mapped reads differ by host species
```{r}
summary(lm(reads.data$mapped_reads_. ~ reads.data$host_species))
plot(lm(reads.data$mapped_reads_. ~ reads.data$host_species))
shapiro.test(residuals(lm(reads.data$mapped_reads_. ~ reads.data$host_species)))
# Residuals of this model are not normally distributed.

# Kruskal-Wallis test (non parametric, because assumptions of ANOVA are not met)
kruskal.test(reads.data$mapped_reads_. ~ reads.data$host_species)
kruskal_effsize(reads.data, mapped_reads_. ~ host_species)
```

ggplot 
```{r}
ggplot(reads.data.ggplot, aes(x = host_species, y = mapped_reads_.)) +
geom_boxplot(alpha = 1, aes(fill = host_species), show.legend = FALSE, outlier.shape = NA)+
geom_point(aes(color = host_species), 
           position = position_jitter(0.075), 
           shape = 16, 
           size = 3, show.legend = FALSE)+
scale_fill_manual(values=c("#63AFF9","#1EA670","#CA0E78","#F39635","#6104BB"))+
scale_color_manual(values=c("black","black","black","black","black"))+
labs(x = "Host Species", 
     y = expression(bolditalic("Methylobacterium") ~ bold("reads (%)")))+
scale_x_discrete(labels = c("ABBA" = "A. balsamea", "THOC" = "T. occidentalis","ACSA" = "A. saccharum", "FAGR" = "F. grandifolia", "COCO" = "C. cornuta"))+
theme_bw()+
theme(text = element_text(family = "Arial"),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(color = "black", size = 11, angle = 0, hjust = 0.5, vjust = 0, face = "italic"),
      axis.text.y = element_text(color = "black", size = 11, angle = 0, hjust = 0, vjust = 0.5),  
      axis.title.x = element_text(color = "black", size = 13, angle = 0, hjust = 0.5, vjust = -1, face = "bold"),
      axis.title.y = element_text(color = "black", size = 13, angle = 90, hjust = 0.5, vjust = 2, face = "bold")
      )
ggsave("../figures/figure_S5_percent_reads_mapped_by_host.tiff", width = 6, height = 4)
```

-################################################################################