---
title: "Pangenome characterization"
output: html_document
date: "2024-07-09"
---

-################################################################################

# Librairies
```{r}
library(tidyverse)
library(data.table)
library(picante)
library(micropan)
```

-################################################################################

# Import data
```{r}
data.pangenome <- readRDS("../rds/data.pangenome.rds")
```

-################################################################################

# Pangenome characterisation

## Gene clusters occurences in genomes
```{r}
gc.unique <- data.pangenome %>%
  distinct(gene_cluster_id, .keep_all = TRUE)
```

Statistics
```{r}
table(gc.unique$genome_occurences)
min(gc.unique[gc.unique$type=="core",]$genome_occurences)
max(gc.unique[gc.unique$type=="accessory",]$genome_occurences)

gc.unique.core <- gc.unique[gc.unique$type=="core",]
gc.unique.acc <- gc.unique[gc.unique$type=="accessory",]

nrow(gc.unique.core) # 2214 core GC
(nrow(gc.unique.core)/nrow(gc.unique))*100 # 3.13% of GC
nrow(gc.unique.acc) # 68,481 accessory GC
(nrow(gc.unique.acc)/nrow(gc.unique))*100 # 96.87% of GC

gc.unique.sing <- gc.unique[gc.unique$genome_occurences == 1,]
nrow(gc.unique.sing) # 38,190 singletons GC
(nrow(gc.unique.sing)/nrow(gc.unique))*100 # 54.02%
```


### Distribution histogram
```{r}
ggplot(gc.unique, aes(x = genome_occurences)) +
    geom_histogram(binwidth = 1, fill = "black") +
    labs(x = "Genome occurences", y = "Counts of gene clusters") +
    scale_y_log10()+
    scale_x_continuous(breaks = seq(0, 100, by = 10)) +
    theme_bw()+
    theme(text = element_text(),
      panel.grid.major.y = element_line(color = "gray", linetype = "solid"),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.x = element_line(color = "gray", linetype = "solid"),
      panel.grid.minor.x = element_blank(),
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(color = "black", size = 16, angle = 0, hjust = 0.5, vjust = 0),
      axis.text.y = element_text(color = "black", size = 16, angle = 0, hjust = 1, vjust = 0.5),  
      axis.title.x = element_text(color = "black", size = 20, angle = 0, hjust = 0.5, vjust = -0.4, face = "bold"),
      axis.title.y = element_text(color = "black", size = 20, angle = 90, hjust = 0.5, vjust = 2, face = "bold")
      )
ggsave("../figures/figure_S2_gc_distribution_genomes_occurences.pdf", width = 12, height = 4, limitsize = FALSE)
```

-################################################################################

# Hypothetical proteins

Count the number of hypothetical proteins
```{r}
data.fct.cov <- readRDS("../rds/data.fct.cov.rds")

# Subset only core genes
data.fct.cov.core <- data.fct.cov[data.fct.cov$type=="core",]
data.fct.cov.core <- droplevels(data.fct.cov.core)
length(unique(data.fct.cov.core$gene_cluster_id))
data.fct.cov.core$functions <- paste(data.fct.cov.core$COG20_FUNCTION, data.fct.cov.core$KOfam, data.fct.cov.core$Pfam, sep = "")

# Filter gene_cluster levels based on functions
hyp.proteins.core <- levels(data.fct.cov.core$gene_cluster_id)[!sapply(levels(data.fct.cov.core$gene_cluster_id), function(x) any(data.fct.cov.core$functions[data.fct.cov.core$gene_cluster_id == x] != ""))]

length(levels(data.fct.cov.core$gene_cluster_id)) # 2214 core GC, in which
length(hyp.proteins.core) # 108 hypothetical proteins (no functional annotation)
(length(hyp.proteins.core)/length(levels(data.fct.cov.core$gene_cluster_id)))*100 # 4.88% of core GC


# Subset only accessory genes
data.fct.cov.acc <- data.fct.cov[data.fct.cov$type=="accessory",]
data.fct.cov.acc <- droplevels(data.fct.cov.acc)
length(unique(data.fct.cov.acc$gene_cluster_id))
data.fct.cov.acc$functions <- paste(data.fct.cov.acc$COG20_FUNCTION, data.fct.cov.acc$KOfam, data.fct.cov.acc$Pfam, sep = "")

# Filter gene_cluster levels based on functions
hyp.proteins.acc <- levels(data.fct.cov.acc$gene_cluster_id)[!sapply(levels(data.fct.cov.acc$gene_cluster_id), function(x) any(data.fct.cov.acc$functions[data.fct.cov.acc$gene_cluster_id == x] != ""))]

length(levels(data.fct.cov.acc$gene_cluster_id)) # 68,481 acc GC
length(hyp.proteins.acc) # 37,968 hypothetical proteins (no functional annotation)
(length(hyp.proteins.acc)/length(levels(data.fct.cov.acc$gene_cluster_id)))*100 # 55.44% of acc GC
```

-################################################################################

# Pangenome openness

Prepare data
```{r}
data.open <- as.data.frame(table(data.pangenome$genome_name, data.pangenome$gene_cluster_id))
data.open <- data.open[,c(1,3,2)]
data.open.comm <- sample2matrix(data.open)
rowSums(data.open.comm)
```

Run rarefaction
```{r}
pan.raref <- rarefaction(data.open.comm,  n.perm = 100)
#saveRDS(pan.raref, "../rds/pan.raref.rds")
```

```{r}
pan.raref <- readRDS("../rds/pan.raref.rds")
```

Summarize the pangenome rarefaction
```{r}
pan.summary <- pan.raref %>%
  pivot_longer(-Genome,
               names_to = "Permutation",
               values_to = "Clusters") %>%
  group_by(Genome) %>%
  summarise(
    mean = mean(Clusters),
    sd = sd(Clusters),
    n = n(),
    se = sd / sqrt(n),
    lower = mean - qt(0.975, df = n - 1) * se,
    upper = mean + qt(0.975, df = n - 1) * se,
    .groups = "drop"
  )
```

Plot
```{r}
ggplot(pan.summary, aes(x = Genome, y = mean)) +
  geom_ribbon(aes(ymin = lower, ymax = upper),
              fill = "red", alpha = 1) +
  geom_line(size = 0.3, colour = "black") +
  scale_y_continuous(
    breaks = seq(0, 70000, by = 10000),
    labels = scales::comma) +
  scale_x_continuous(breaks = seq(0, 100, by = 10)) +
  labs(x = "Genomes (n)",
    y = "Gene clusters (n)") +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color = "lightgray", linewidth = 0.5, linetype = "dotted"),
    panel.grid.major.x = element_line(color = "lightgray", linewidth = 0.5, linetype = "dotted"),
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(color = "black", size = 11),
    axis.text.y = element_text(color = "black", size = 11),
    axis.title.x = element_text(color = "black", size = 13, face = "bold"),
    axis.title.y = element_text(color = "black", size = 13, face = "bold")
  )
ggsave("../figures/figure_S3_open_pangenome.pdf", width = 6, height = 4)
```

Heaps test
```{r}
heaps.test <- heaps(data.open.comm, n.perm = 100)
heaps.test
```

-################################################################################